language: python

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: 2.7
    - os: linux
      dist: trusty
      sudo: required
      python: 3.3
    - os: linux
      dist: trusty
      sudo: required
      python: 3.4
    - os: linux
      dist: trusty
      sudo: required
      python: 3.5
    - os: linux
      dist: trusty
      sudo: required
      python: 3.6
#    - os: linux
#      dist: trusty
#      sudo: required
#      python: pypy
# Travis does not support yet Python installation on OSX (see https://github.com/travis-ci/travis-ci/issues/2312).
# We will therefore only test with the preinstalled Python 2.7
    - os: osx
      osx_image: xcode8
      language: generic

install:
    - pip install hypothesis Cython

script:
    - python setup.py build_ext -i
    - python test.py
    - python -c "import cydoctest, pyroaring; cydoctest.testmod(pyroaring)" -v
